version: 2

project_name: tryve

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: tryve
    main: ./cmd/tryve
    binary: tryve
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: tryve
    name_template: "tryve_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: liemle3893
    name: go-tryve
  draft: false
  prerelease: auto
